### ISSUE TITLE
OS version requirements?

### ISSUE THREAD

**Issue by staze** [scriptingosx/diskspace#3]
Howdy! 

Just curious if you know which OS's this will run under? Was thinking of deploying to our fleet via Jamf to get real diskspace info... 

Thanks!

**Comment by scriptingosx** [comment]
As the readme states, this should work 10.14 and higher.

**Comment by staze** [comment]
sorry, I didn't even see the "icon" showing 10.14+. was looking for the text, etc. 

Thank you!
